# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7b3dda7ab8b01ae25af80d8467da7f929621738484af0e2ac587e1334a031a6e5d1426a7f77fe8fb9c0a02a62730d71e90ee5445e62d0223835e5d689050b22

test:
  secret_key_base: e4cc65ef11ac00a2326854e363828e522e6fdc2b7872416903e7dacda40c2aead20113fbd0fb1ca98bbb29580de267302c99b4d7a2549aba0a371d9faa4d9cb2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
